# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsf_options',
            name='bsf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.BSF'),
        ),
        migrations.AlterField(
            model_name='car',
            name='listing_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='pcf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PCF'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.VDF'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vhf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.VHF'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.BSF'),
        ),
    ]
