# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171011_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcf',
            name='vid',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
