# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pcf_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcf',
            name='model_number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
