# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170921_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(max_length=11),
        ),
    ]
