# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170924_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('msrp', models.IntegerField(max_length=11)),
                ('warranty_start', models.CharField(max_length=20)),
                ('model_year', models.IntegerField(max_length=4)),
                ('model_detail', models.TextField()),
                ('color', models.TextField()),
                ('production_month', models.CharField(max_length=7)),
                ('interior', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BSF_Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11)),
                ('value', models.TextField()),
                ('bsf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BSF')),
            ],
        ),
    ]
