# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171019_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetryCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_code', models.CharField(default=b'', max_length=17)),
            ],
        ),
    ]
