# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171025_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='active',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
