# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_car_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine_size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
