# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171201_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated',
            field=models.DateField(max_length=255),
        ),
    ]
