# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171201_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsf',
            name='production_month',
            field=models.DateField(max_length=10),
        ),
    ]
