# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171201_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='listing_date',
            field=models.DateField(max_length=255),
        ),
    ]
