# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20171222_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='sold_date',
            field=models.DateField(max_length=30),
        ),
    ]
