# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171223_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='listing_date',
            field=models.CharField(max_length=30),
        ),
    ]
