# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20171224_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsf',
            name='warranty_start',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
