# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20171227_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcf',
            name='air_cooled',
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='auto_trans',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='body_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='gap_to_msrp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='listing_age',
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='longhood',
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='lwb_seats',
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='option_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='option_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='pccb',
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='placeholder',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='produced_globally',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='produced_usa',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='pts',
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='same_counts',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='vid',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='widebody',
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
    ]
