# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20171227_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Site'),
        ),
        migrations.AlterField(
            model_name='site',
            name='created',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='updated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vdf',
            name='model_detail',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vdf',
            name='model_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='vdf',
            name='region',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='vdf',
            name='year',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='vhf',
            name='recall_count',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='vhf',
            name='title_check',
            field=models.TextField(blank=True, null=True),
        ),
    ]
