# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-30 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20171227_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pcf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PCF'),
        ),
    ]
