# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20171229_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='listing_date',
            field=models.DateField(max_length=255),
        ),
    ]
