# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-10 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20180114_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='listing_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
