# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-22 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180210_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='updated',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
