# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-26 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20180222_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True),
        ),
    ]
