# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-26 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180326_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsf',
            name='model_year',
            field=models.IntegerField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='car',
            name='listing_model_detail',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='listing_title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='listing_transmission',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='listing_year',
            field=models.IntegerField(blank=True, db_index=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='model_number',
            field=models.CharField(blank=True, db_index=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pcf',
            name='vid',
            field=models.CharField(db_index=True, max_length=6),
        ),
    ]
